# Generated by Django 2.2.14 on 2020-08-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('TotoalNumber', models.IntegerField(default=0)),
                ('TotalPrice', models.FloatField(default=0)),
            ],
        ),
    ]
